/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hrm.view;

import com.hrm.dao.EmployeeDAO;
import com.hrm.dao.SalaryDAO;
import com.hrm.model.Employee;
import com.hrm.model.Salary;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Hoang Vu
 */
public class SalaryNhanVien extends javax.swing.JFrame {
    private Employee employee;
    // private Salary salary;
    // private Position position;
    // private SalaryNhanVien NhanVienframe;

    public SalaryNhanVien() {
        init();
    }

    private void init() {
        loaddata();
        initComponents();
        setVisible(true);
        addEvents();
    }

    public SalaryNhanVien(Employee employee) {
        this.employee = employee;
        initComponents(); // Đảm bảo phương thức này được gọi
        init();
    }

    public Employee getEmployee() {
        return employee;
    }

    private void addEvents() {

        jblback.addActionListener((java.awt.event.ActionEvent evt) -> {
            // System.out.println("hihihi");
            // MainFrame mainframe = new MainFrame(employee);
            // mainframe.setVisible(true);
            // dispose();
        });
        btnYeuCauThayDoi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                System.out.println("Button clicked!"); // Xác nhận sự kiện đã được kích hoạt
                showSalaryChangeDialog(evt); // Gọi hàm hiển thị dialog
            }
        });

    }

    private void showSalaryChangeDialog(ActionEvent evt) {
        // Tạo dialog
        JDialog dialog = new JDialog(this, "Yêu cầu thay đổi lương", true);
        dialog.setSize(400, 250);
        dialog.setLayout(new GridLayout(4, 1, 10, 10));
        dialog.setLocationRelativeTo(this);

        // Tạo giao diện trong dialog
        JPanel panelSalary = createInputPanel("Mức lương đề xuất:", new JTextField(20));
        JPanel panelReason = createInputPanel("Lý do thay đổi:", new JTextField(20));
        JPanel panelButtons = createButtonPanel(dialog, panelSalary, panelReason);

        dialog.add(panelSalary);
        dialog.add(panelReason);
        dialog.add(panelButtons);

        dialog.setVisible(true);
    }

    /**
     * Tạo panel nhập liệu với nhãn và ô nhập
     */
    private JPanel createInputPanel(String labelText, JTextField textField) {
        JPanel panel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JLabel label = new JLabel(labelText);
        panel.add(label);
        panel.add(textField);
        return panel;
    }

    /**
     * Tạo panel chứa nút Hủy và Gửi
     */
    private JPanel createButtonPanel(JDialog dialog, JPanel panelSalary, JPanel panelReason) {
        JPanel panelButtons = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JButton btnSubmit = new JButton("Gửi yêu cầu");
        JButton btnCancel = new JButton("Hủy");

        panelButtons.add(btnSubmit);
        panelButtons.add(btnCancel);

        // Xử lý nút Hủy
        // btnCancel.addActionListener((e) -> dialog.dispose());
        //
        // // Xử lý nút Gửi yêu cầu
        // btnSubmit.addActionListener((e) -> handleSalaryChangeRequest(dialog,
        // panelSalary, panelReason));

        return panelButtons;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtViTri = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnYeuCauThayDoi = new javax.swing.JButton();
        txtTongLuongTheoGio = new javax.swing.JLabel();
        txtTongLuongTangCa = new javax.swing.JLabel();
        txtThuong = new javax.swing.JLabel();
        txtKhauTru = new javax.swing.JLabel();
        txtChuyenCan = new javax.swing.JLabel();
        txtNgayHieuLuc = new javax.swing.JLabel();
        txtTongLuong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 245, 249));

        jPanel1.setBackground(new java.awt.Color(245, 143, 82));

        jblback.setText("Quay lại");
        jblback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblbackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel1.setText("Chi tiet phieu luong");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jblback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jblback)
                                        .addComponent(jLabel1))
                                .addContainerGap(16, Short.MAX_VALUE)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Chi tiết lương  ");

        txtViTri.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Chuyên cần");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Tổng lương theo giờ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Tổng lương theo tăng ca");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Thưởng");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Khấu trừ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Tổng lương");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Ngày hiệu lực");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        btnYeuCauThayDoi.setText("Yêu cầu thay đổi");
        btnYeuCauThayDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeuCauThayDoiActionPerformed(evt);
            }
        });

        txtTongLuongTheoGio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTongLuongTheoGio.setText(" ");

        txtTongLuongTangCa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTongLuongTangCa.setText(" ");

        txtThuong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtThuong.setText(" ");

        txtKhauTru.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtKhauTru.setText(" ");

        txtChuyenCan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtChuyenCan.setText(" ");

        txtNgayHieuLuc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNgayHieuLuc.setText(" ");

        txtTongLuong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTongLuong.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(btnYeuCauThayDoi))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                layout.createSequentialGroup()
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(jLabel6,
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        246,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel7,
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING))
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(
                                                                                                        txtTongLuongTheoGio,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        246,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(
                                                                                                        txtTongLuongTangCa,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        246,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(jLabel8)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(txtThuong,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                246,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(jLabel5)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(txtChuyenCan,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                246,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(jLabel9)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(txtKhauTru,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                246,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel10)
                                                                                                .addGap(191, 191, 191)
                                                                                                .addComponent(
                                                                                                        txtTongLuong,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        246,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel11)
                                                                                                .addGap(169, 169, 169)
                                                                                                .addComponent(
                                                                                                        txtNgayHieuLuc,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        246,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                .addGap(40, 40, 40)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                261,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel12,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                92,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtHoTen,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 246,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtViTri,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)))
                                                .addGap(96, 96, 96)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel12))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(txtTongLuongTheoGio))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtTongLuongTangCa)
                                                        .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(txtChuyenCan))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(txtThuong))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(txtKhauTru)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(btnYeuCauThayDoi))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtTongLuong)
                                                        .addComponent(jLabel10))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNgayHieuLuc)
                                        .addComponent(jLabel11))
                                .addContainerGap(204, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblbackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jblbackActionPerformed
        System.out.println("hihihi");
        new MainFrame(employee);
        dispose();
    }// GEN-LAST:event_jblbackActionPerformed

    private void btnYeuCauThayDoiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnYeuCauThayDoiActionPerformed

    }// GEN-LAST:event_btnYeuCauThayDoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnYeuCauThayDoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jblback;
    private javax.swing.JLabel txtChuyenCan;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JLabel txtHoTen;
    private javax.swing.JLabel txtKhauTru;
    private javax.swing.JLabel txtNgayHieuLuc;
    private javax.swing.JLabel txtThuong;
    private javax.swing.JLabel txtTongLuong;
    private javax.swing.JLabel txtTongLuongTangCa;
    private javax.swing.JLabel txtTongLuongTheoGio;
    private javax.swing.JLabel txtViTri;
    // End of variables declaration//GEN-END:variables

    private void loaddata() {
        this.txtHoTen.setText(employee.getName());
        SalaryDAO salaryDao = new SalaryDAO();
        Salary salary = salaryDao.selectByEmployeeID(employee.getId());
        EmployeeDAO employeeDao = new EmployeeDAO();
        Employee employee1 = employeeDao.selectByID(employee.getId());
        this.txtViTri.setText(employee1.getPosition().getName());
        this.txtTongLuongTheoGio.setText(salary.getHourly_salary() + "");
        this.txtTongLuongTangCa.setText(salary.getOvertime_hourly_salary() + "");
        this.txtChuyenCan.setText(salary.getAttendance() + "");
        this.txtThuong.setText(salary.getBonus() + "");
        this.txtKhauTru.setText(salary.getDeductions() + "");
        this.txtTongLuong.setText(salary.getnet_salary() + "");
        this.txtNgayHieuLuc.setText(salary.getPayday() + "");
        this.txtGhiChu.setText(salary.getNote() + " ");
    }

}